# Chemigran TCM Granule Inventory — 551 SKUs
# Fields: id, chinese, pinyin, english, extract_ratio, raw_per_g, raw_per_bag,
#         categories, tcm_functions, contraindications

HERBS = [
    {"id":1,"chinese":"矮地茶","pinyin":"Ài Dì Chá","english":"Japanese Ardisia Herb","extract_ratio":0.83,"raw_per_g":6,"raw_per_bag":5,"categories":["Respiratory","Clear-Heat"],"tcm_functions":["Clears heat","Resolves phlegm","Stops cough","Promotes urination"],"contraindications":[]},
    {"id":2,"chinese":"艾叶","pinyin":"Ài Yè","english":"Mugwort Leaf","extract_ratio":0.75,"raw_per_g":4,"raw_per_bag":3,"categories":["Gynecology","Warming","Hemostasis"],"tcm_functions":["Warms meridians","Stops bleeding","Disperses cold","Calms fetus"],"contraindications":["Yin deficiency heat"]},
    {"id":3,"chinese":"醋艾炭","pinyin":"Cù Ài Tàn","english":"Vinegar-processed Mugwort Charcoal","extract_ratio":0.6,"raw_per_g":5,"raw_per_bag":3,"categories":["Hemostasis","Gynecology"],"tcm_functions":["Stops bleeding","Warms uterus"],"contraindications":[]},
    {"id":4,"chinese":"巴戟天","pinyin":"Bā Jǐ Tiān","english":"Morinda Root","extract_ratio":3.57,"raw_per_g":1.4,"raw_per_bag":5,"categories":["Kidney Yang","Men's Health","Aging"],"tcm_functions":["Tonifies Kidney Yang","Strengthens sinews and bones","Expels wind-damp"],"contraindications":["Yin deficiency fire","Damp-heat"]},
    {"id":5,"chinese":"制巴戟天","pinyin":"Zhì Bā Jǐ Tiān","english":"Processed Morinda Root","extract_ratio":3.85,"raw_per_g":1.3,"raw_per_bag":5,"categories":["Kidney Yang","Men's Health","Aging"],"tcm_functions":["Tonifies Kidney Yang","Strengthens bones","Warms lower back"],"contraindications":["Yin deficiency fire"]},
    {"id":6,"chinese":"盐巴戟天","pinyin":"Yán Bā Jǐ Tiān","english":"Salt-processed Morinda Root","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Kidney Yang","Men's Health"],"tcm_functions":["Tonifies Kidney Yang","Directs action to Kidney channel"],"contraindications":["Yin deficiency fire"]},
    {"id":7,"chinese":"白扁豆","pinyin":"Bái Biǎn Dòu","english":"White Hyacinth Bean","extract_ratio":2.0,"raw_per_g":5,"raw_per_bag":10,"categories":["Spleen","Gut Health","Summer Heat"],"tcm_functions":["Tonifies Spleen","Resolves dampness","Clears summer heat"],"contraindications":[]},
    {"id":8,"chinese":"炒白扁豆","pinyin":"Chǎo Bái Biǎn Dòu","english":"Roasted White Hyacinth Bean","extract_ratio":1.82,"raw_per_g":5.5,"raw_per_bag":10,"categories":["Spleen","Gut Health"],"tcm_functions":["Tonifies Spleen","Stops diarrhoea","Resolves dampness"],"contraindications":[]},
    {"id":9,"chinese":"制白附子","pinyin":"Zhì Bái Fù Zǐ","english":"Processed Typhonium Rhizome","extract_ratio":1.36,"raw_per_g":2.2,"raw_per_bag":3,"categories":["Wind-Phlegm","Neurological"],"tcm_functions":["Resolves wind-phlegm","Stops spasm","Dissipates nodules"],"contraindications":["Pregnancy","Blood deficiency"]},
    {"id":10,"chinese":"白及","pinyin":"Bái Jí","english":"Bletilla Rhizome","extract_ratio":0.6,"raw_per_g":5,"raw_per_bag":3,"categories":["Hemostasis","Lung","Skin"],"tcm_functions":["Stops bleeding","Reduces swelling","Generates flesh","Astringes Lung"],"contraindications":["External pathogen cough"]},
    {"id":11,"chinese":"百部(对叶百部)","pinyin":"Bǎi Bù","english":"Stemona Root","extract_ratio":3.57,"raw_per_g":1.4,"raw_per_bag":5,"categories":["Respiratory","Antiparasitic"],"tcm_functions":["Moistens Lung","Stops cough","Kills parasites"],"contraindications":[]},
    {"id":12,"chinese":"蜜百部(对叶百部)","pinyin":"Mì Bǎi Bù","english":"Honey-processed Stemona Root","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Respiratory"],"tcm_functions":["Moistens Lung","Stops chronic cough"],"contraindications":[]},
    {"id":13,"chinese":"菝葜","pinyin":"Bá Qiā","english":"Smilax Rhizome","extract_ratio":1.33,"raw_per_g":7.5,"raw_per_bag":10,"categories":["Clear-Heat","Damp-Heat","Joints"],"tcm_functions":["Clears heat","Resolves toxins","Expels wind-damp"],"contraindications":[]},
    {"id":14,"chinese":"白果仁","pinyin":"Bái Guǒ Rén","english":"Ginkgo Seed","extract_ratio":1.61,"raw_per_g":3.1,"raw_per_bag":5,"categories":["Respiratory","Kidney","Aging"],"tcm_functions":["Stops cough","Astringes Lung","Reduces leukorrhoea","Benefits brain"],"contraindications":["Pregnancy","Children (limit dose)"]},
    {"id":15,"chinese":"百合(卷丹)","pinyin":"Bǎi Hé","english":"Lily Bulb","extract_ratio":1.2,"raw_per_g":5,"raw_per_bag":6,"categories":["Lung","Sleep","Calm-Shen"],"tcm_functions":["Moistens Lung","Clears Heart heat","Calms Shen","Stops cough"],"contraindications":["Wind-cold cough","Spleen deficiency with damp"]},
    {"id":16,"chinese":"蜜百合(卷丹)","pinyin":"Mì Bǎi Hé","english":"Honey-processed Lily Bulb","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Lung","Sleep","Calm-Shen"],"tcm_functions":["Moistens Lung","Nourishes Heart yin","Calms Shen"],"contraindications":[]},
    {"id":17,"chinese":"白花蛇舌草","pinyin":"Bái Huā Shé Shé Cǎo","english":"Hedyotis / White Snakeweed","extract_ratio":2.83,"raw_per_g":5.3,"raw_per_bag":15,"categories":["Clear-Heat","Anti-Tumor","Immune"],"tcm_functions":["Clears heat","Resolves toxins","Promotes urination","Anti-inflammatory"],"contraindications":["Deficiency cold"]},
    {"id":18,"chinese":"白茅根","pinyin":"Bái Máo Gēn","english":"Imperata Rhizome / Cogon Root","extract_ratio":2.0,"raw_per_g":2.5,"raw_per_bag":5,"categories":["Hemostasis","Clear-Heat","Urinary"],"tcm_functions":["Cools blood","Stops bleeding","Clears Lung heat","Promotes urination"],"contraindications":["Spleen deficiency"]},
    {"id":19,"chinese":"白前(柳叶白前)","pinyin":"Bái Qián","english":"Cynanchum Root","extract_ratio":1.32,"raw_per_g":3.8,"raw_per_bag":5,"categories":["Respiratory"],"tcm_functions":["Descends Lung Qi","Resolves phlegm","Stops cough"],"contraindications":[]},
    {"id":20,"chinese":"白芍","pinyin":"Bái Sháo","english":"White Peony Root","extract_ratio":1.33,"raw_per_g":4.5,"raw_per_bag":6,"categories":["Blood Tonic","Liver","Women's Health","Pain"],"tcm_functions":["Nourishes blood","Softens Liver","Alleviates pain","Astringes yin"],"contraindications":["Yang deficiency cold abdomen"]},
    {"id":21,"chinese":"炒白芍","pinyin":"Chǎo Bái Sháo","english":"Roasted White Peony Root","extract_ratio":1.33,"raw_per_g":4.5,"raw_per_bag":6,"categories":["Blood Tonic","Liver","Women's Health"],"tcm_functions":["Nourishes blood","Softens Liver","Harmonises Spleen"],"contraindications":[]},
    {"id":22,"chinese":"酒白芍","pinyin":"Jiǔ Bái Sháo","english":"Wine-processed White Peony Root","extract_ratio":1.33,"raw_per_g":4.5,"raw_per_bag":6,"categories":["Blood Tonic","Liver","Women's Health"],"tcm_functions":["Nourishes blood","Invigorates blood","Regulates menstruation"],"contraindications":[]},
    {"id":23,"chinese":"白头翁","pinyin":"Bái Tóu Wēng","english":"Chinese Pulsatilla Root","extract_ratio":3.33,"raw_per_g":3,"raw_per_bag":10,"categories":["Clear-Heat","Gut Health"],"tcm_functions":["Clears heat","Resolves toxins","Cools blood","Stops dysentery"],"contraindications":["Deficiency cold diarrhoea"]},
    {"id":24,"chinese":"白薇(白薇)","pinyin":"Bái Wēi","english":"Cynanchum Atratum Root","extract_ratio":1.43,"raw_per_g":3.5,"raw_per_bag":5,"categories":["Clear-Heat","Women's Health","Fever"],"tcm_functions":["Clears heat","Cools blood","Promotes urination","Relieves toxins"],"contraindications":[]},
    {"id":25,"chinese":"白鲜皮","pinyin":"Bái Xiǎn Pí","english":"Dictamnus Bark","extract_ratio":1.35,"raw_per_g":3.7,"raw_per_bag":5,"categories":["Clear-Heat","Skin","Damp-Heat"],"tcm_functions":["Clears heat","Resolves dampness","Expels wind","Relieves itching"],"contraindications":["Spleen-Stomach deficiency"]},
    {"id":26,"chinese":"白英","pinyin":"Bái Yīng","english":"Bittersweet Herb","extract_ratio":0.76,"raw_per_g":6.6,"raw_per_bag":5,"categories":["Clear-Heat","Anti-Tumor"],"tcm_functions":["Clears heat","Resolves toxins","Promotes urination","Anti-cancer support"],"contraindications":["Pregnancy"]},
    {"id":27,"chinese":"白芷(白芷)","pinyin":"Bái Zhǐ","english":"Angelica Dahurica Root","extract_ratio":1.67,"raw_per_g":3,"raw_per_bag":5,"categories":["Exterior Release","Pain","ENT","Skin"],"tcm_functions":["Expels wind-cold","Relieves pain","Opens nasal orifices","Reduces swelling"],"contraindications":["Yin deficiency heat","Blood deficiency headache"]},
    {"id":28,"chinese":"白芷(杭白芷)","pinyin":"Bái Zhǐ (Háng)","english":"Hangzhou Angelica Root","extract_ratio":1.25,"raw_per_g":4,"raw_per_bag":5,"categories":["Exterior Release","Pain","ENT"],"tcm_functions":["Expels wind","Relieves headache","Opens nasal passages"],"contraindications":[]},
    {"id":29,"chinese":"白术","pinyin":"Bái Zhú","english":"Atractylodes Macrocephala Rhizome","extract_ratio":3.85,"raw_per_g":1.3,"raw_per_bag":5,"categories":["Spleen","Gut Health","Qi Tonic"],"tcm_functions":["Tonifies Spleen Qi","Dries dampness","Promotes urination","Calms fetus"],"contraindications":["Yin deficiency thirst","Excess heat"]},
    {"id":30,"chinese":"麸炒白术","pinyin":"Fū Chǎo Bái Zhú","english":"Bran-fried Atractylodes","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Spleen","Gut Health","Qi Tonic"],"tcm_functions":["Tonifies Spleen","Dries dampness","Strengthens digestion"],"contraindications":[]},
    {"id":31,"chinese":"败酱草(黄花败酱)","pinyin":"Bài Jiàng Cǎo","english":"Patrinia Herb","extract_ratio":1.2,"raw_per_g":7.5,"raw_per_bag":9,"categories":["Clear-Heat","Gut Health","Gynecology"],"tcm_functions":["Clears heat","Resolves toxins","Expels pus","Invigorates blood"],"contraindications":["Spleen deficiency"]},
    {"id":32,"chinese":"柏子仁","pinyin":"Bǎi Zǐ Rén","english":"Biota Seed / Arborvitae Seed","extract_ratio":1.0,"raw_per_g":5,"raw_per_bag":5,"categories":["Sleep","Calm-Shen","Heart","Constipation"],"tcm_functions":["Nourishes Heart yin","Calms Shen","Moistens intestines","Stops sweating"],"contraindications":["Loose stools","Phlegm-damp"]},
    {"id":33,"chinese":"半边莲","pinyin":"Bàn Biān Lián","english":"Lobelia Chinensis Herb","extract_ratio":3.57,"raw_per_g":2.8,"raw_per_bag":10,"categories":["Clear-Heat","Edema","Anti-Tumor"],"tcm_functions":["Clears heat","Resolves toxins","Promotes urination","Reduces edema"],"contraindications":["Deficiency cold"]},
    {"id":34,"chinese":"板蓝根","pinyin":"Bǎn Lán Gēn","english":"Isatis Root / Woad Root","extract_ratio":4.5,"raw_per_g":2,"raw_per_bag":9,"categories":["Clear-Heat","Immune","Antiviral","Respiratory"],"tcm_functions":["Clears heat","Resolves toxins","Cools blood","Benefits throat"],"contraindications":["Spleen-Stomach deficiency cold"]},
    {"id":35,"chinese":"法半夏","pinyin":"Fǎ Bàn Xià","english":"Processed Pinellia (Licorice method)","extract_ratio":1.47,"raw_per_g":3.4,"raw_per_bag":5,"categories":["Phlegm","Gut Health","Nausea"],"tcm_functions":["Dries dampness","Resolves phlegm","Descends rebellious Qi","Stops vomiting"],"contraindications":["Yin deficiency dry cough","Bleeding"]},
    {"id":36,"chinese":"姜半夏","pinyin":"Jiāng Bàn Xià","english":"Ginger-processed Pinellia","extract_ratio":2.27,"raw_per_g":2.2,"raw_per_bag":5,"categories":["Phlegm","Nausea","Gut Health"],"tcm_functions":["Resolves phlegm","Stops vomiting","Warms Stomach"],"contraindications":["Yin deficiency","Pregnancy"]},
    {"id":37,"chinese":"清半夏","pinyin":"Qīng Bàn Xià","english":"Alum-processed Pinellia","extract_ratio":1.56,"raw_per_g":3.2,"raw_per_bag":5,"categories":["Phlegm","Respiratory"],"tcm_functions":["Dries dampness","Resolves phlegm","Reduces swelling"],"contraindications":["Pregnancy"]},
    {"id":38,"chinese":"半枝莲","pinyin":"Bàn Zhī Lián","english":"Scutellaria Barbata Herb","extract_ratio":3.75,"raw_per_g":4,"raw_per_bag":15,"categories":["Clear-Heat","Anti-Tumor","Immune"],"tcm_functions":["Clears heat","Resolves toxins","Invigorates blood","Promotes urination"],"contraindications":["Blood deficiency without toxin"]},
    {"id":39,"chinese":"北沙参","pinyin":"Běi Shā Shēn","english":"Glehniae Radix / North Glehnia Root","extract_ratio":2.4,"raw_per_g":2.5,"raw_per_bag":6,"categories":["Lung Yin","Stomach Yin","Aging"],"tcm_functions":["Nourishes Lung and Stomach yin","Clears heat","Generates fluids"],"contraindications":["Wind-cold cough","Spleen deficiency"]},
    {"id":40,"chinese":"荜茇","pinyin":"Bì Bá","english":"Long Pepper Fruit","extract_ratio":0.6,"raw_per_g":5,"raw_per_bag":3,"categories":["Warming","Gut Health","Pain"],"tcm_functions":["Warms middle jiao","Disperses cold","Alleviates pain","Stops vomiting"],"contraindications":["Yin deficiency heat","Pregnancy"]},
    {"id":41,"chinese":"萹蓄","pinyin":"Biǎn Xù","english":"Common Knotgrass Herb","extract_ratio":0.83,"raw_per_g":6,"raw_per_bag":5,"categories":["Urinary","Clear-Damp-Heat"],"tcm_functions":["Clears damp-heat","Promotes urination","Expels stones","Kills parasites"],"contraindications":["Spleen deficiency"]},
    {"id":42,"chinese":"醋鳖甲","pinyin":"Cù Biē Jiǎ","english":"Vinegar-processed Tortoise Plastron","extract_ratio":1.67,"raw_per_g":6,"raw_per_bag":10,"categories":["Yin Tonic","Thyroid","Anti-Tumor","Women's Health"],"tcm_functions":["Nourishes yin","Subdues Yang","Softens hardness","Disperses masses","Cools blood"],"contraindications":["Pregnancy","Spleen deficiency"]},
    {"id":43,"chinese":"槟榔","pinyin":"Bīng Láng","english":"Areca Seed","extract_ratio":0.5,"raw_per_g":10,"raw_per_bag":5,"categories":["Antiparasitic","Gut Health","Qi-Moving"],"tcm_functions":["Kills parasites","Promotes Qi movement","Reduces accumulation","Promotes urination"],"contraindications":["Qi deficiency","Spleen deficiency"]},
    {"id":44,"chinese":"炒槟榔","pinyin":"Chǎo Bīng Láng","english":"Roasted Areca Seed","extract_ratio":0.5,"raw_per_g":10,"raw_per_bag":5,"categories":["Gut Health","Qi-Moving"],"tcm_functions":["Moves Qi","Reduces stagnation","Relieves bloating"],"contraindications":[]},
    {"id":45,"chinese":"焦槟榔","pinyin":"Jiāo Bīng Láng","english":"Charred Areca Seed","extract_ratio":0.5,"raw_per_g":10,"raw_per_bag":5,"categories":["Gut Health"],"tcm_functions":["Reduces food stagnation","Stops diarrhoea"],"contraindications":[]},
    {"id":46,"chinese":"薄荷","pinyin":"Bò He","english":"Peppermint Herb","extract_ratio":0.81,"raw_per_g":3.7,"raw_per_bag":3,"categories":["Exterior Release","Liver","ENT","Stress"],"tcm_functions":["Disperses wind-heat","Clears head and eyes","Resolves Liver Qi","Benefits throat"],"contraindications":["Sweating","Qi deficiency"]},
    {"id":47,"chinese":"补骨脂","pinyin":"Bǔ Gǔ Zhī","english":"Psoralea Fruit","extract_ratio":0.9,"raw_per_g":6.7,"raw_per_bag":6,"categories":["Kidney Yang","Aging","Men's Health","Thyroid"],"tcm_functions":["Tonifies Kidney Yang","Warms Spleen","Astringes Jing","Stops diarrhoea"],"contraindications":["Yin deficiency fire","Constipation"]},
    {"id":48,"chinese":"盐补骨脂","pinyin":"Yán Bǔ Gǔ Zhī","english":"Salt-processed Psoralea Fruit","extract_ratio":1.2,"raw_per_g":5,"raw_per_bag":6,"categories":["Kidney Yang","Aging"],"tcm_functions":["Tonifies Kidney Yang","Directed to Kidney channel"],"contraindications":["Yin deficiency"]},
    {"id":49,"chinese":"布渣叶","pinyin":"Bù Zhā Yè","english":"Microcos Leaf","extract_ratio":1.67,"raw_per_g":6,"raw_per_bag":10,"categories":["Gut Health","Clear-Damp-Heat"],"tcm_functions":["Clears heat","Resolves dampness","Promotes digestion","Relieves thirst"],"contraindications":[]},
    {"id":50,"chinese":"白蔹","pinyin":"Bái Liǎn","english":"Ampelopsis Root","extract_ratio":1.25,"raw_per_g":4,"raw_per_bag":5,"categories":["Clear-Heat","Skin","Anti-Tumor"],"tcm_functions":["Clears heat","Resolves toxins","Reduces swelling","Generates flesh"],"contraindications":["Deficiency cold"]},
    {"id":55,"chinese":"苍术(北苍术)","pinyin":"Cāng Zhú","english":"Atractylodes Rhizome","extract_ratio":1.85,"raw_per_g":2.7,"raw_per_bag":5,"categories":["Damp","Spleen","Gut Health","Joints"],"tcm_functions":["Dries dampness","Strengthens Spleen","Expels wind-cold-damp","Brightens vision"],"contraindications":["Yin deficiency","Qi deficiency sweating"]},
    {"id":56,"chinese":"麸炒苍术(北苍术)","pinyin":"Fū Chǎo Cāng Zhú","english":"Bran-fried Atractylodes","extract_ratio":2.5,"raw_per_g":2,"raw_per_bag":5,"categories":["Damp","Spleen"],"tcm_functions":["Strengthens Spleen","Dries dampness (milder)"],"contraindications":[]},
    {"id":60,"chinese":"北柴胡","pinyin":"Běi Chái Hú","english":"Bupleurum Root","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Liver","Stress","Fever","Women's Health"],"tcm_functions":["Relieves Liver Qi stagnation","Reduces fever","Raises Yang Qi","Harmonises Shao Yang"],"contraindications":["Liver Yang rising","Yin deficiency"]},
    {"id":61,"chinese":"醋北柴胡","pinyin":"Cù Běi Chái Hú","english":"Vinegar-processed Bupleurum","extract_ratio":1.71,"raw_per_g":3.5,"raw_per_bag":6,"categories":["Liver","Stress","Women's Health"],"tcm_functions":["Moves Liver Qi","Relieves pain","Directed to Liver channel"],"contraindications":["Yin deficiency"]},
    {"id":68,"chinese":"陈皮","pinyin":"Chén Pí","english":"Aged Tangerine Peel","extract_ratio":2.5,"raw_per_g":2,"raw_per_bag":5,"categories":["Gut Health","Phlegm","Qi-Moving"],"tcm_functions":["Regulates Qi","Dries dampness","Resolves phlegm","Harmonises Spleen-Stomach"],"contraindications":["Qi deficiency","Dry cough"]},
    {"id":69,"chinese":"赤芍(芍药)","pinyin":"Chì Sháo","english":"Red Peony Root","extract_ratio":1.8,"raw_per_g":3.3,"raw_per_bag":6,"categories":["Blood Stasis","Clear-Heat","Gynecology","Thyroid"],"tcm_functions":["Invigorates blood","Disperses stasis","Clears heat","Cools blood","Relieves pain"],"contraindications":["Blood deficiency without stasis","Pregnancy"]},
    {"id":77,"chinese":"川芎","pinyin":"Chuān Xiōng","english":"Ligusticum Chuanxiong Rhizome","extract_ratio":1.67,"raw_per_g":3,"raw_per_bag":5,"categories":["Blood Stasis","Pain","Women's Health","Headache"],"tcm_functions":["Invigorates blood","Moves Qi","Expels wind","Relieves pain","Regulates menstruation"],"contraindications":["Yin deficiency fire","Heavy menstruation","Pregnancy"]},
    {"id":80,"chinese":"煅磁石","pinyin":"Duàn Cí Shí","english":"Calcined Magnetite","extract_ratio":0.8,"raw_per_g":12.5,"raw_per_bag":10,"categories":["Calm-Shen","Sleep","Tinnitus"],"tcm_functions":["Anchors Yang","Calms Liver","Calms Shen","Benefits hearing and vision"],"contraindications":["Spleen deficiency"]},
    {"id":81,"chinese":"刺五加","pinyin":"Cì Wǔ Jiā","english":"Siberian Ginseng / Eleuthero","extract_ratio":0.83,"raw_per_g":12,"raw_per_bag":10,"categories":["Qi Tonic","Adaptogen","Aging","Stress"],"tcm_functions":["Tonifies Spleen Qi","Nourishes Heart","Calms Shen","Improves stamina"],"contraindications":["Excess heat"]},
    {"id":82,"chinese":"酒苁蓉(管花肉苁蓉)","pinyin":"Jiǔ Ròu Cōng Róng","english":"Wine-processed Cistanche (Tubulosa)","extract_ratio":2.38,"raw_per_g":2.1,"raw_per_bag":5,"categories":["Kidney Yang","Men's Health","Aging","Constipation"],"tcm_functions":["Tonifies Kidney Yang","Replenishes Jing","Moistens intestines","Supports fertility"],"contraindications":["Yin deficiency fire","Diarrhoea"]},
    {"id":83,"chinese":"酒苁蓉(肉苁蓉)","pinyin":"Jiǔ Ròu Cōng Róng (Cōng Róng)","english":"Wine-processed Cistanche","extract_ratio":3.13,"raw_per_g":1.6,"raw_per_bag":5,"categories":["Kidney Yang","Men's Health","Aging"],"tcm_functions":["Tonifies Kidney Yang","Replenishes Jing and blood","Lubricates intestines"],"contraindications":["Excess fire","Diarrhoea"]},
    {"id":84,"chinese":"肉苁蓉(管花肉苁蓉)","pinyin":"Ròu Cōng Róng","english":"Cistanche Herb","extract_ratio":2.27,"raw_per_g":2.2,"raw_per_bag":5,"categories":["Kidney Yang","Men's Health","Aging"],"tcm_functions":["Tonifies Kidney Yang","Nourishes Jing","Moistens intestines"],"contraindications":["Excess heat","Loose stools"]},
    {"id":94,"chinese":"大黄(药用大黄)","pinyin":"Dà Huáng","english":"Rhubarb Root and Rhizome","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Gut Health","Clear-Heat","Blood Stasis","Thyroid"],"tcm_functions":["Purges heat","Moves stool","Clears heat","Invigorates blood","Reduces inflammation"],"contraindications":["Pregnancy","Menstruation","Qi and blood deficiency","Spleen-Stomach weakness"]},
    {"id":101,"chinese":"大枣","pinyin":"Dà Zǎo","english":"Jujube / Chinese Date","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Qi Tonic","Blood Tonic","Calm-Shen","Women's Health"],"tcm_functions":["Tonifies Spleen Qi","Nourishes blood","Calms Shen","Harmonises herbs"],"contraindications":["Phlegm-damp","Food stagnation","Parasites"]},
    {"id":105,"chinese":"丹参","pinyin":"Dān Shēn","english":"Salvia Root / Dan Shen","extract_ratio":2.5,"raw_per_g":2,"raw_per_bag":5,"categories":["Blood Stasis","Heart","Stress","Sleep","Thyroid","Women's Health"],"tcm_functions":["Invigorates blood","Breaks stasis","Clears Heart heat","Calms Shen","Cools blood","Relieves pain"],"contraindications":["Warfarin interaction","No blood stasis","Pregnancy"]},
    {"id":106,"chinese":"酒丹参","pinyin":"Jiǔ Dān Shēn","english":"Wine-processed Salvia Root","extract_ratio":2.5,"raw_per_g":2,"raw_per_bag":5,"categories":["Blood Stasis","Heart","Women's Health"],"tcm_functions":["Invigorates blood (enhanced)","Warms channels","Relieves pain"],"contraindications":["Warfarin"]},
    {"id":108,"chinese":"当归","pinyin":"Dāng Guī","english":"Angelica Sinensis Root","extract_ratio":4.0,"raw_per_g":1.5,"raw_per_bag":6,"categories":["Blood Tonic","Women's Health","Pain","Constipation"],"tcm_functions":["Tonifies blood","Invigorates blood","Regulates menstruation","Relieves pain","Moistens intestines"],"contraindications":["Pregnancy (caution)","Diarrhoea","Excess dampness","Heavy menstruation"]},
    {"id":109,"chinese":"酒当归","pinyin":"Jiǔ Dāng Guī","english":"Wine-processed Angelica","extract_ratio":4.0,"raw_per_g":1.5,"raw_per_bag":6,"categories":["Blood Tonic","Women's Health","Blood Stasis"],"tcm_functions":["Tonifies and invigorates blood (enhanced)","Warms channels","Regulates menses"],"contraindications":["Pregnancy","Diarrhoea"]},
    {"id":111,"chinese":"党参(党参)","pinyin":"Dǎng Shēn","english":"Codonopsis Root","extract_ratio":3.0,"raw_per_g":1,"raw_per_bag":3,"categories":["Qi Tonic","Spleen","Gut Health","Immune","Aging"],"tcm_functions":["Tonifies Middle Jiao Qi","Strengthens Spleen","Nourishes blood","Promotes fluid generation"],"contraindications":["Excess heat","Excess conditions"]},
    {"id":117,"chinese":"生地黄","pinyin":"Shēng Dì Huáng","english":"Fresh/Dried Rehmannia Root","extract_ratio":3.57,"raw_per_g":1.4,"raw_per_bag":5,"categories":["Yin Tonic","Clear-Heat","Blood Cooling","Women's Health"],"tcm_functions":["Clears heat","Cools blood","Nourishes yin","Generates fluids","Stops bleeding"],"contraindications":["Spleen deficiency with diarrhoea","Phlegm-damp"]},
    {"id":119,"chinese":"熟地黄","pinyin":"Shú Dì Huáng","english":"Prepared Rehmannia Root","extract_ratio":3.85,"raw_per_g":1.3,"raw_per_bag":5,"categories":["Yin Tonic","Blood Tonic","Kidney","Aging","Women's Health"],"tcm_functions":["Tonifies Kidney yin","Replenishes Jing","Nourishes blood","Benefits marrow"],"contraindications":["Phlegm-damp","Spleen deficiency with diarrhoea"]},
    {"id":129,"chinese":"杜仲","pinyin":"Dù Zhòng","english":"Eucommia Bark","extract_ratio":1.0,"raw_per_g":6,"raw_per_bag":6,"categories":["Kidney Yang","Aging","Men's Health","Joints","Thyroid"],"tcm_functions":["Tonifies Liver and Kidney","Strengthens sinews and bones","Calms fetus","Lowers blood pressure"],"contraindications":["Yin deficiency fire"]},
    {"id":130,"chinese":"盐杜仲","pinyin":"Yán Dù Zhòng","english":"Salt-processed Eucommia Bark","extract_ratio":1.2,"raw_per_g":5,"raw_per_bag":6,"categories":["Kidney Yang","Aging","Men's Health","Joints"],"tcm_functions":["Tonifies Kidney (directed)","Strengthens lower back","Supports joints"],"contraindications":["Yin deficiency fire"]},
    {"id":134,"chinese":"阿胶","pinyin":"Ē Jiāo","english":"Donkey-hide Gelatin","extract_ratio":2.22,"raw_per_g":0.9,"raw_per_bag":2,"categories":["Blood Tonic","Hemostasis","Lung","Women's Health","Skin","Aging"],"tcm_functions":["Nourishes blood","Stops bleeding","Nourishes Lung yin","Calms fetus","Benefits skin and hair"],"contraindications":["Phlegm-damp","Spleen deficiency with diarrhoea"]},
    {"id":146,"chinese":"茯苓","pinyin":"Fú Líng","english":"Poria / Indian Bread","extract_ratio":0.8,"raw_per_g":12.5,"raw_per_bag":10,"categories":["Spleen","Gut Health","Calm-Shen","Damp","Immune"],"tcm_functions":["Strengthens Spleen","Resolves dampness","Calms Shen","Promotes urination","Tonifies Middle Jiao"],"contraindications":["Yin deficiency without dampness"]},
    {"id":148,"chinese":"茯神","pinyin":"Fú Shén","english":"Poria with Hostwood / Spirit Poria","extract_ratio":0.5,"raw_per_g":20,"raw_per_bag":10,"categories":["Sleep","Calm-Shen","Heart","Stress"],"tcm_functions":["Calms Heart Shen","Quiets spirit","Relieves anxiety","Improves sleep"],"contraindications":[]},
    {"id":155,"chinese":"黑芝麻","pinyin":"Hēi Zhī Ma","english":"Black Sesame Seed","extract_ratio":0.8,"raw_per_g":12.5,"raw_per_bag":10,"categories":["Blood Tonic","Yin Tonic","Aging","Hair","Constipation"],"tcm_functions":["Nourishes Liver-Kidney","Nourishes blood","Lubricates intestines","Benefits hair"],"contraindications":["Loose stools","Phlegm-damp"]},
    {"id":156,"chinese":"甘草(甘草)","pinyin":"Gān Cǎo","english":"Licorice Root","extract_ratio":1.0,"raw_per_g":3,"raw_per_bag":3,"categories":["Harmonising","Qi Tonic","Anti-inflammatory","Envoy"],"tcm_functions":["Tonifies Spleen Qi","Harmonises herbs","Clears heat","Relieves toxins","Stops cough"],"contraindications":["Edema","Hypertension (large dose)"]},
    {"id":157,"chinese":"炙甘草(甘草)","pinyin":"Zhì Gān Cǎo","english":"Honey-fried Licorice Root","extract_ratio":1.5,"raw_per_g":2,"raw_per_bag":3,"categories":["Harmonising","Qi Tonic","Heart","Envoy"],"tcm_functions":["Tonifies Spleen Qi","Nourishes Heart","Harmonises formula","Stops palpitations"],"contraindications":["Edema","Hypertension"]},
    {"id":168,"chinese":"葛根","pinyin":"Gé Gēn","english":"Pueraria Root / Kudzu Root","extract_ratio":4.0,"raw_per_g":2.5,"raw_per_bag":10,"categories":["Exterior Release","Neck Tension","Thyroid","Women's Health","Metabolic"],"tcm_functions":["Releases muscle layer","Clears heat","Generates fluids","Raises Yang","Relieves neck stiffness"],"contraindications":["Stomach cold"]},
    {"id":170,"chinese":"枸杞子","pinyin":"Gǒu Qǐ Zǐ","english":"Wolfberry / Goji Berry","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Yin Tonic","Liver","Kidney","Aging","Eyes","Women's Health"],"tcm_functions":["Nourishes Liver-Kidney yin","Nourishes blood","Benefits vision","Supplements Jing"],"contraindications":["Excess heat","Diarrhoea"]},
    {"id":171,"chinese":"钩藤(钩藤)","pinyin":"Gōu Téng","english":"Uncaria Stem with Hooks","extract_ratio":0.63,"raw_per_g":8,"raw_per_bag":5,"categories":["Liver Wind","Neurological","Headache","Blood Pressure"],"tcm_functions":["Clears Liver heat","Extinguishes wind","Stops spasms","Relieves headache","Lowers BP"],"contraindications":["No heat or Liver Yang rising"]},
    {"id":196,"chinese":"合欢花(合欢花)","pinyin":"Hé Huān Huā","english":"Mimosa Tree Flower","extract_ratio":1.25,"raw_per_g":4,"raw_per_bag":5,"categories":["Sleep","Calm-Shen","Stress","Depression"],"tcm_functions":["Relieves emotional constraint","Calms Shen","Reduces anxiety","Lifts mood","Improves sleep"],"contraindications":["Pregnancy (caution)"]},
    {"id":200,"chinese":"合欢皮","pinyin":"Hé Huān Pí","english":"Mimosa Tree Bark","extract_ratio":0.6,"raw_per_g":10,"raw_per_bag":6,"categories":["Sleep","Calm-Shen","Stress","Fractures"],"tcm_functions":["Calms Shen","Relieves depression","Invigorates blood","Reduces swelling"],"contraindications":["Pregnancy"]},
    {"id":207,"chinese":"红参","pinyin":"Hóng Shēn","english":"Red Ginseng","extract_ratio":3.33,"raw_per_g":1.5,"raw_per_bag":5,"categories":["Qi Tonic","Yang Tonic","Aging","Immune","Adaptogen"],"tcm_functions":["Strongly tonifies Yuan Qi","Rescues Yang","Benefits Heart","Generates fluids","Calms Shen"],"contraindications":["Excess heat","Yin deficiency fire","Hypertension"]},
    {"id":211,"chinese":"虎杖","pinyin":"Hǔ Zhàng","english":"Japanese Knotweed / Polygonum Cuspidatum","extract_ratio":2.0,"raw_per_g":4.5,"raw_per_bag":9,"categories":["Blood Stasis","Clear-Heat","Thyroid","Antiviral","Liver","Gut Health"],"tcm_functions":["Invigorates blood","Clears heat","Resolves toxins","Promotes urination","Stops cough"],"contraindications":["Pregnancy"]},
    {"id":218,"chinese":"黄精(多花黄精)","pinyin":"Huáng Jīng","english":"Polygonatum Rhizome / Solomon's Seal","extract_ratio":3.85,"raw_per_g":1.3,"raw_per_bag":5,"categories":["Yin Tonic","Qi Tonic","Aging","Adaptogen","Lung","Kidney"],"tcm_functions":["Tonifies Spleen Qi","Nourishes Lung and Kidney yin","Replenishes Jing","Adapatogenic"],"contraindications":["Phlegm-damp","Spleen deficiency with diarrhoea"]},
    {"id":219,"chinese":"酒黄精(多花黄精)","pinyin":"Jiǔ Huáng Jīng","english":"Wine-processed Polygonatum","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Yin Tonic","Qi Tonic","Aging","Adaptogen"],"tcm_functions":["Tonifies Jing (enhanced)","Nourishes all three Treasures","Longevity herb"],"contraindications":[]},
    {"id":222,"chinese":"黄芪(蒙古黄芪)","pinyin":"Huáng Qí","english":"Astragalus Root","extract_ratio":4.0,"raw_per_g":2.5,"raw_per_bag":10,"categories":["Qi Tonic","Immune","Aging","Men's Health","Women's Health"],"tcm_functions":["Tonifies Wei Qi","Strengthens Spleen","Raises Yang","Promotes urination","Generates flesh"],"contraindications":["Exterior excess","Yin deficiency with heat","Stagnation"]},
    {"id":223,"chinese":"炙黄芪(蒙古黄芪)","pinyin":"Zhì Huáng Qí","english":"Honey-fried Astragalus Root","extract_ratio":3.13,"raw_per_g":1.6,"raw_per_bag":5,"categories":["Qi Tonic","Aging","Immune","Spleen"],"tcm_functions":["Strongly tonifies Spleen and Lung Qi","Strengthens Wei Qi","Raises Middle Jiao Yang"],"contraindications":["Exterior excess"]},
    {"id":224,"chinese":"黄芩","pinyin":"Huáng Qín","english":"Scutellaria Root / Skullcap Root","extract_ratio":2.27,"raw_per_g":2.2,"raw_per_bag":5,"categories":["Clear-Heat","Respiratory","Thyroid","Gut Health","Antiviral"],"tcm_functions":["Clears heat","Dries dampness","Purges fire","Stops bleeding","Calms fetus","Anti-inflammatory"],"contraindications":["Spleen-Stomach deficiency cold"]},
    {"id":229,"chinese":"何首乌","pinyin":"Hé Shǒu Wū","english":"Polygonum Multiflorum Root","extract_ratio":0.45,"raw_per_g":6.7,"raw_per_bag":3,"categories":["Blood Tonic","Liver","Kidney"],"tcm_functions":["Nourishes blood","Tonifies Liver-Kidney","Moistens intestines"],"contraindications":["Phlegm-damp","Loose stools","Hepatotoxicity risk (raw form)"]},
    {"id":230,"chinese":"制何首乌","pinyin":"Zhì Hé Shǒu Wū","english":"Processed Polygonum Root (Black Bean method)","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Blood Tonic","Yin Tonic","Aging","Hair","Kidney"],"tcm_functions":["Tonifies Liver-Kidney","Replenishes Jing and blood","Benefits hair","Reduces cholesterol"],"contraindications":["Phlegm-damp","Loose stools"]},
    {"id":231,"chinese":"红景天","pinyin":"Hóng Jǐng Tiān","english":"Rhodiola Rosea","extract_ratio":1.0,"raw_per_g":3,"raw_per_bag":3,"categories":["Adaptogen","Aging","Stress","Immune","Altitude"],"tcm_functions":["Tonifies Qi","Invigorates blood","Calms Shen","Relieves fatigue","Adapatogenic"],"contraindications":[]},
    {"id":237,"chinese":"鸡内金","pinyin":"Jī Nèi Jīn","english":"Chicken Gizzard Lining","extract_ratio":0.63,"raw_per_g":8,"raw_per_bag":5,"categories":["Gut Health","Food Stagnation","Kidney","Urinary"],"tcm_functions":["Dissolves food stagnation","Strengthens Spleen","Astringes Jing","Dissolves stones"],"contraindications":[]},
    {"id":238,"chinese":"炒鸡内金","pinyin":"Chǎo Jī Nèi Jīn","english":"Roasted Chicken Gizzard Lining","extract_ratio":0.63,"raw_per_g":8,"raw_per_bag":5,"categories":["Gut Health","Food Stagnation"],"tcm_functions":["Dissolves food stagnation (enhanced)","Strengthens Spleen-Stomach"],"contraindications":[]},
    {"id":242,"chinese":"鸡血藤","pinyin":"Jī Xuè Téng","english":"Spatholobus Stem / Millettia Root","extract_ratio":1.64,"raw_per_g":5.5,"raw_per_bag":9,"categories":["Blood Tonic","Blood Stasis","Women's Health","Joints"],"tcm_functions":["Tonifies blood","Invigorates blood","Unblocks meridians","Relaxes sinews","Regulates menstruation"],"contraindications":["Pregnancy (large dose)"]},
    {"id":250,"chinese":"金银花","pinyin":"Jīn Yín Huā","english":"Honeysuckle Flower / Lonicera","extract_ratio":2.0,"raw_per_g":3,"raw_per_bag":6,"categories":["Clear-Heat","Immune","Antiviral","Respiratory","Anti-Tumor"],"tcm_functions":["Clears heat","Resolves toxins","Cools blood","Anti-inflammatory","Antiviral"],"contraindications":["Spleen deficiency cold"]},
    {"id":261,"chinese":"菊花","pinyin":"Jú Huā","english":"Chrysanthemum Flower","extract_ratio":1.43,"raw_per_g":3.5,"raw_per_bag":5,"categories":["Liver","Eyes","Blood Pressure","Headache","Clear-Heat"],"tcm_functions":["Clears Liver heat","Benefits vision","Subdues Yang","Expels wind-heat","Calms Liver"],"contraindications":["Qi deficiency","Cold stomach"]},
    {"id":262,"chinese":"决明子(钝叶决明)","pinyin":"Jué Míng Zǐ","english":"Cassia Seed","extract_ratio":2.0,"raw_per_g":5,"raw_per_bag":10,"categories":["Liver","Eyes","Constipation","Blood Pressure"],"tcm_functions":["Clears Liver heat","Benefits vision","Lubricates intestines","Lowers cholesterol"],"contraindications":["Spleen deficiency with diarrhoea","Pregnancy"]},
    {"id":270,"chinese":"苦参","pinyin":"Kǔ Shēn","english":"Sophora Root","extract_ratio":1.0,"raw_per_g":5,"raw_per_bag":5,"categories":["Clear-Damp-Heat","Skin","Gut Health","Antiparasitic"],"tcm_functions":["Clears heat","Dries dampness","Kills parasites","Promotes urination","Anti-inflammatory"],"contraindications":["Spleen-Stomach deficiency","Incompatible with 藜芦 Li Lu"]},
    {"id":283,"chinese":"莲子","pinyin":"Lián Zǐ","english":"Lotus Seed","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Spleen","Kidney","Calm-Shen","Gut Health"],"tcm_functions":["Tonifies Spleen","Astringes Kidney","Calms Shen","Stops diarrhoea"],"contraindications":["Constipation","Exterior conditions"]},
    {"id":284,"chinese":"莲子心","pinyin":"Lián Zǐ Xīn","english":"Lotus Plumule","extract_ratio":0.97,"raw_per_g":3.1,"raw_per_bag":3,"categories":["Clear-Heat","Sleep","Calm-Shen","Heart"],"tcm_functions":["Clears Heart fire","Calms Shen","Stops bleeding","Astringes Jing"],"contraindications":["Spleen-Stomach deficiency cold"]},
    {"id":286,"chinese":"灵芝(赤芝)","pinyin":"Líng Zhī","english":"Ganoderma / Reishi Mushroom","extract_ratio":0.48,"raw_per_g":12.5,"raw_per_bag":6,"categories":["Aging","Immune","Sleep","Calm-Shen","Adaptogen","Qi Tonic","Anti-Tumor"],"tcm_functions":["Tonifies all Three Treasures","Calms Shen","Strengthens Wei Qi","Nourishes Heart","Stops cough","Anti-tumor support"],"contraindications":[]},
    {"id":290,"chinese":"龙眼肉","pinyin":"Lóng Yǎn Ròu","english":"Longan Fruit Flesh","extract_ratio":2.73,"raw_per_g":1.1,"raw_per_bag":3,"categories":["Blood Tonic","Calm-Shen","Heart","Spleen","Women's Health"],"tcm_functions":["Nourishes Heart blood","Tonifies Spleen","Calms Shen","Supplements blood","Improves memory"],"contraindications":["Phlegm-fire","Damp-heat"]},
    {"id":295,"chinese":"罗布麻叶","pinyin":"Luó Bù Má Yè","english":"Dogbane Leaf / Apocynum Leaf","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Blood Pressure","Liver","Calm-Shen"],"tcm_functions":["Calms Liver Yang","Reduces blood pressure","Clears heat","Promotes urination"],"contraindications":["Spleen-Stomach deficiency"]},
    {"id":300,"chinese":"龙骨","pinyin":"Lóng Gǔ","english":"Dragon Bone (Fossilised Mammal Bone)","extract_ratio":0.6,"raw_per_g":25,"raw_per_bag":15,"categories":["Calm-Shen","Sleep","Anxiety","Thyroid","Liver Yang"],"tcm_functions":["Anchors and calms Shen","Calms Liver","Astringes Jing","Stops sweating","Softens masses"],"contraindications":["Exterior conditions","Damp-heat"]},
    {"id":301,"chinese":"煅龙骨","pinyin":"Duàn Lóng Gǔ","english":"Calcined Dragon Bone","extract_ratio":0.6,"raw_per_g":25,"raw_per_bag":15,"categories":["Calm-Shen","Sleep","Hemostasis"],"tcm_functions":["Anchors Shen (stronger astringing)","Stops bleeding","Stops sweating"],"contraindications":[]},
    {"id":316,"chinese":"牡蛎(近江牡蛎)","pinyin":"Mǔ Lì","english":"Oyster Shell","extract_ratio":0.8,"raw_per_g":12.5,"raw_per_bag":10,"categories":["Thyroid","Calm-Shen","Liver Yang","Sleep","Nodules"],"tcm_functions":["Anchors Yang","Calms Liver","Softens hardness","Dissipates nodules","Astringes sweating"],"contraindications":["Excess cold conditions"]},
    {"id":317,"chinese":"煅牡蛎(近江牡蛎)","pinyin":"Duàn Mǔ Lì","english":"Calcined Oyster Shell","extract_ratio":0.8,"raw_per_g":12.5,"raw_per_bag":10,"categories":["Thyroid","Calm-Shen","Nodules","Hemostasis"],"tcm_functions":["Softens hardness (stronger)","Dissipates nodules","Astringes and stops sweating","Stops bleeding"],"contraindications":[]},
    {"id":318,"chinese":"麦冬(川麦冬)","pinyin":"Mài Dōng","english":"Ophiopogon Root","extract_ratio":2.73,"raw_per_g":1.1,"raw_per_bag":3,"categories":["Lung Yin","Stomach Yin","Heart","Sleep","Aging"],"tcm_functions":["Nourishes Lung and Stomach yin","Clears Heart heat","Calms Shen","Generates fluids","Stops cough"],"contraindications":["Wind-cold cough","Spleen deficiency with diarrhoea"]},
    {"id":325,"chinese":"玫瑰花","pinyin":"Méi Guī Huā","english":"Rose Flower","extract_ratio":0.81,"raw_per_g":3.7,"raw_per_bag":3,"categories":["Liver","Stress","Women's Health","Qi-Moving","Mood"],"tcm_functions":["Moves Liver Qi","Relieves depression","Invigorates blood","Harmonises Stomach","Lifts mood"],"contraindications":["Yin deficiency fire"]},
    {"id":327,"chinese":"墨旱莲","pinyin":"Mò Hàn Lián","english":"Eclipta Herb","extract_ratio":1.33,"raw_per_g":4.5,"raw_per_bag":6,"categories":["Yin Tonic","Liver","Kidney","Hemostasis","Women's Health","Aging"],"tcm_functions":["Nourishes Liver-Kidney yin","Cools blood","Stops bleeding","Benefits hair"],"contraindications":["Spleen deficiency cold"]},
    {"id":328,"chinese":"牡丹皮","pinyin":"Mǔ Dān Pí","english":"Moutan Bark / Tree Peony Root Bark","extract_ratio":2.0,"raw_per_g":3,"raw_per_bag":6,"categories":["Clear-Heat","Blood Cooling","Women's Health","Thyroid","Menopause"],"tcm_functions":["Clears heat","Cools blood","Invigorates blood","Clears deficiency heat","Disperses stasis"],"contraindications":["Pregnancy","Heavy menstruation","Blood deficiency"]},
    {"id":333,"chinese":"木香","pinyin":"Mù Xiāng","english":"Costus Root / Saussurea Root","extract_ratio":2.31,"raw_per_g":1.3,"raw_per_bag":3,"categories":["Qi-Moving","Gut Health","Pain","Spleen"],"tcm_functions":["Moves Qi","Relieves pain","Strengthens Spleen","Regulates Liver and Spleen"],"contraindications":["Yin deficiency","Fluid consumption"]},
    {"id":344,"chinese":"女贞子","pinyin":"Nǚ Zhēn Zǐ","english":"Ligustrum Fruit / Privet Fruit","extract_ratio":1.82,"raw_per_g":3.3,"raw_per_bag":6,"categories":["Yin Tonic","Kidney","Liver","Aging","Women's Health","Menopause","Hair"],"tcm_functions":["Nourishes Liver-Kidney yin","Clears deficiency heat","Benefits vision","Benefits hair"],"contraindications":["Spleen deficiency cold","Diarrhoea"]},
    {"id":345,"chinese":"酒女贞子","pinyin":"Jiǔ Nǚ Zhēn Zǐ","english":"Wine-processed Ligustrum Fruit","extract_ratio":2.31,"raw_per_g":2.6,"raw_per_bag":6,"categories":["Yin Tonic","Kidney","Liver","Aging","Menopause"],"tcm_functions":["Nourishes Liver-Kidney yin (enhanced)","Directed to Liver channel","Benefits bone density"],"contraindications":[]},
    {"id":360,"chinese":"芡实","pinyin":"Qiàn Shí","english":"Gordon Euryale Seed / Fox Nut","extract_ratio":0.9,"raw_per_g":10,"raw_per_bag":9,"categories":["Kidney","Spleen","Gut Health","Women's Health"],"tcm_functions":["Tonifies Spleen","Astringes Kidney","Stops diarrhoea","Resolves dampness","Stabilises Jing"],"contraindications":["Exterior conditions","Constipation","Food stagnation"]},
    {"id":361,"chinese":"麸炒芡实","pinyin":"Fū Chǎo Qiàn Shí","english":"Bran-fried Gordon Euryale Seed","extract_ratio":1.34,"raw_per_g":6.7,"raw_per_bag":9,"categories":["Spleen","Gut Health","Kidney"],"tcm_functions":["Tonifies Spleen (enhanced)","Stops diarrhoea","Astringes Kidney"],"contraindications":[]},
    {"id":383,"chinese":"肉桂","pinyin":"Ròu Guì","english":"Cinnamon Bark / Cassia Bark","extract_ratio":0.55,"raw_per_g":5.5,"raw_per_bag":3,"categories":["Kidney Yang","Warming","Men's Health","Aging","Pain"],"tcm_functions":["Warms Kidney Yang","Disperses cold","Alleviates pain","Guides fire to origin","Invigorates blood"],"contraindications":["Yin deficiency fire","Pregnancy","Bleeding disorders"]},
    {"id":386,"chinese":"人参","pinyin":"Rén Shēn","english":"Ginseng Root","extract_ratio":2.0,"raw_per_g":2.5,"raw_per_bag":5,"categories":["Qi Tonic","Adaptogen","Aging","Immune","Cognitive"],"tcm_functions":["Strongly tonifies Yuan Qi","Tonifies Spleen and Lung","Generates fluids","Calms Shen","Benefits cognitive function"],"contraindications":["Excess heat","Yin deficiency fire","Hypertension"]},
    {"id":388,"chinese":"三七粉","pinyin":"Sān Qī Fěn","english":"Notoginseng Powder / Tienchi Ginseng","extract_ratio":0.67,"raw_per_g":1.5,"raw_per_bag":1,"categories":["Blood Stasis","Hemostasis","Cardiovascular","Pain","Thyroid"],"tcm_functions":["Invigorates blood","Stops bleeding","Reduces swelling","Relieves pain","Softens masses"],"contraindications":["Pregnancy","Blood deficiency without stasis"]},
    {"id":398,"chinese":"砂仁(阳春砂)","pinyin":"Shā Rén","english":"Amomum / Cardamom Fruit","extract_ratio":0.67,"raw_per_g":4.5,"raw_per_bag":3,"categories":["Gut Health","Spleen","Warming","Nausea","Pregnancy"],"tcm_functions":["Aromatically transforms dampness","Warms Spleen","Promotes Qi movement","Calms fetus","Stops vomiting"],"contraindications":["Yin deficiency heat","Fluid deficiency"]},
    {"id":402,"chinese":"山药","pinyin":"Shān Yào","english":"Dioscorea / Chinese Yam","extract_ratio":2.5,"raw_per_g":4,"raw_per_bag":10,"categories":["Qi Tonic","Yin Tonic","Spleen","Kidney","Lung","Gut Health","Aging"],"tcm_functions":["Tonifies Spleen Qi","Nourishes Lung and Kidney yin","Stabilises Jing","Supplements blood"],"contraindications":["Excess dampness","Food stagnation"]},
    {"id":403,"chinese":"麸炒山药","pinyin":"Fū Chǎo Shān Yào","english":"Bran-fried Dioscorea","extract_ratio":2.5,"raw_per_g":4,"raw_per_bag":10,"categories":["Spleen","Gut Health","Qi Tonic"],"tcm_functions":["Tonifies Spleen (enhanced)","Stops diarrhoea","Strengthens digestion"],"contraindications":[]},
    {"id":404,"chinese":"炒山楂(山里红)","pinyin":"Chǎo Shān Zhā","english":"Roasted Hawthorn Berry","extract_ratio":3.0,"raw_per_g":2,"raw_per_bag":6,"categories":["Gut Health","Food Stagnation","Cardiovascular","Blood Stasis"],"tcm_functions":["Dissolves food stagnation","Invigorates blood","Reduces fat/cholesterol","Astringes intestines"],"contraindications":["Spleen deficiency without stagnation","Peptic ulcer (excess)"]},
    {"id":405,"chinese":"山楂(山里红)","pinyin":"Shān Zhā","english":"Hawthorn Berry","extract_ratio":3.0,"raw_per_g":2,"raw_per_bag":6,"categories":["Gut Health","Cardiovascular","Blood Stasis"],"tcm_functions":["Dissolves food stagnation (meat/fat)","Invigorates blood","Reduces cholesterol"],"contraindications":["Spleen deficiency","Peptic ulcer"]},
    {"id":407,"chinese":"山萸肉","pinyin":"Shān Yú Ròu","english":"Cornus Fruit / Asiatic Cornelian Cherry","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Kidney","Liver","Yin Tonic","Aging","Men's Health","Sweating","Women's Health"],"tcm_functions":["Tonifies Liver-Kidney","Astringes Jing","Stabilises menstruation","Stops excessive sweating","Tonifies Yang"],"contraindications":["Damp-heat","Excess fire"]},
    {"id":408,"chinese":"酒萸肉","pinyin":"Jiǔ Yú Ròu","english":"Wine-processed Cornus Fruit","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Kidney","Liver","Yin Tonic","Aging","Men's Health","Menopause"],"tcm_functions":["Tonifies Liver-Kidney (enhanced)","Astringes Jing","Directed to Liver channel"],"contraindications":[]},
    {"id":425,"chinese":"首乌藤","pinyin":"Shǒu Wū Téng","english":"Polygonum Multiflorum Stem / Night-Blooming Stem","extract_ratio":1.5,"raw_per_g":6,"raw_per_bag":9,"categories":["Sleep","Blood Tonic","Calm-Shen","Skin","Joints"],"tcm_functions":["Nourishes blood","Calms Shen","Improves sleep","Unblocks meridians","Expels wind"],"contraindications":["Phlegm-damp"]},
    {"id":429,"chinese":"酸枣仁","pinyin":"Suān Zǎo Rén","english":"Ziziphus Seed / Jujube Seed","extract_ratio":2.5,"raw_per_g":4,"raw_per_bag":10,"categories":["Sleep","Calm-Shen","Heart","Liver","Stress"],"tcm_functions":["Nourishes Heart blood","Calms Shen","Anchors spirit","Stops sweating","Improves sleep quality"],"contraindications":["Excess fire","Acute exterior conditions"]},
    {"id":430,"chinese":"炒酸枣仁","pinyin":"Chǎo Suān Zǎo Rén","english":"Roasted Ziziphus Seed","extract_ratio":2.5,"raw_per_g":4,"raw_per_bag":10,"categories":["Sleep","Calm-Shen","Heart","Liver","Stress"],"tcm_functions":["Nourishes Heart blood (enhanced sedative)","Calms Shen","Primary herb for insomnia","Reduces anxiety"],"contraindications":["Excess fire"]},
    {"id":431,"chinese":"锁阳","pinyin":"Suǒ Yáng","english":"Cynomorium Herb / Suo Yang","extract_ratio":2.5,"raw_per_g":2,"raw_per_bag":5,"categories":["Kidney Yang","Men's Health","Aging","Constipation"],"tcm_functions":["Tonifies Kidney Yang","Replenishes Jing","Strengthens sinews","Lubricates intestines"],"contraindications":["Yin deficiency fire","Diarrhoea"]},
    {"id":442,"chinese":"天冬","pinyin":"Tiān Dōng","english":"Asparagus Root / Asparagus Cochinchinensis","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Lung Yin","Kidney Yin","Aging","Anti-Tumor"],"tcm_functions":["Nourishes Lung and Kidney yin","Clears heat","Moistens dryness","Generates fluids"],"contraindications":["Spleen deficiency cold","Wind-cold cough"]},
    {"id":443,"chinese":"天麻","pinyin":"Tiān Má","english":"Gastrodia Rhizome","extract_ratio":1.25,"raw_per_g":4,"raw_per_bag":5,"categories":["Liver Wind","Neurological","Headache","Dizziness","Blood Pressure"],"tcm_functions":["Extinguishes Wind","Stops spasms","Relieves headache","Calms Liver Yang","Improves cognitive function"],"contraindications":["Blood deficiency"]},
    {"id":451,"chinese":"土茯苓","pinyin":"Tǔ Fú Líng","english":"Smilax Glabra Rhizome","extract_ratio":3.75,"raw_per_g":4,"raw_per_bag":15,"categories":["Clear-Damp-Heat","Joints","Skin","Anti-Tumor","Urinary"],"tcm_functions":["Clears heat","Resolves toxins","Resolves dampness","Unblocks meridians","Benefits joints"],"contraindications":[]},
    {"id":452,"chinese":"菟丝子(南方菟丝子)","pinyin":"Tù Sī Zǐ","english":"Cuscuta Seed / Dodder Seed","extract_ratio":1.2,"raw_per_g":5,"raw_per_bag":6,"categories":["Kidney Yang","Yin Tonic","Men's Health","Women's Health","Aging","Eyes"],"tcm_functions":["Tonifies Kidney Yang and Yin","Stabilises Jing","Brightens vision","Calms fetus","Stops diarrhoea"],"contraindications":["Yin deficiency fire","Constipation"]},
    {"id":453,"chinese":"盐菟丝子(南方菟丝子)","pinyin":"Yán Tù Sī Zǐ","english":"Salt-processed Cuscuta Seed","extract_ratio":1.33,"raw_per_g":4.5,"raw_per_bag":6,"categories":["Kidney Yang","Men's Health","Aging"],"tcm_functions":["Tonifies Kidney (directed)","Stabilises Jing","Strengthens lower back"],"contraindications":[]},
    {"id":462,"chinese":"五味子","pinyin":"Wǔ Wèi Zǐ","english":"Schisandra Berry / Five-Flavour Berry","extract_ratio":1.88,"raw_per_g":1.6,"raw_per_bag":3,"categories":["Lung","Kidney","Calm-Shen","Sleep","Aging","Adaptogen","Liver"],"tcm_functions":["Astringes Lung Qi","Nourishes Kidney","Generates fluids","Calms Shen","Restrains sweating","Adaptogenic","Hepatoprotective"],"contraindications":["Exterior conditions","Interior excess heat"]},
    {"id":474,"chinese":"西洋参","pinyin":"Xī Yáng Shēn","english":"American Ginseng Root","extract_ratio":1.5,"raw_per_g":2,"raw_per_bag":3,"categories":["Qi Tonic","Yin Tonic","Lung","Aging","Adaptogen","Cognitive"],"tcm_functions":["Tonifies Qi","Nourishes yin","Clears heat","Generates fluids","Calms Shen","Adaptogenic"],"contraindications":["Yang deficiency cold","Spleen deficiency diarrhoea"]},
    {"id":476,"chinese":"夏枯草","pinyin":"Xià Kū Cǎo","english":"Prunella Spike / Self-Heal","extract_ratio":1.38,"raw_per_g":6.5,"raw_per_bag":9,"categories":["Thyroid","Clear-Heat","Liver","Nodules","Blood Pressure","Anti-Tumor"],"tcm_functions":["Clears Liver fire","Dissipates nodules","Softens hardness","Reduces blood pressure","Anti-tumor support"],"contraindications":["Spleen-Stomach deficiency"]},
    {"id":479,"chinese":"香附","pinyin":"Xiāng Fù","english":"Cyperus Rhizome / Nut Grass","extract_ratio":1.0,"raw_per_g":5,"raw_per_bag":5,"categories":["Liver","Stress","Women's Health","Pain","Qi-Moving"],"tcm_functions":["Moves Liver Qi","Regulates menstruation","Relieves pain","Harmonises Qi"],"contraindications":["Qi deficiency","Blood deficiency without stagnation"]},
    {"id":480,"chinese":"醋香附","pinyin":"Cù Xiāng Fù","english":"Vinegar-processed Cyperus Rhizome","extract_ratio":1.25,"raw_per_g":4,"raw_per_bag":5,"categories":["Liver","Women's Health","Pain","Stress"],"tcm_functions":["Moves Liver Qi (stronger pain relief)","Regulates menstruation","Directed to Liver/Blood"],"contraindications":["Qi deficiency"]},
    {"id":495,"chinese":"玄参","pinyin":"Xuán Shēn","english":"Scrophularia Root","extract_ratio":3.33,"raw_per_g":1.5,"raw_per_bag":5,"categories":["Yin Tonic","Thyroid","Clear-Heat","Nodules","Immune"],"tcm_functions":["Nourishes yin","Clears heat","Softens hardness","Resolves toxins","Benefits throat"],"contraindications":["Spleen deficiency cold","Incompatible with 藜芦 Li Lu"]},
    {"id":497,"chinese":"延胡索","pinyin":"Yán Hú Suǒ","english":"Corydalis Rhizome","extract_ratio":1.11,"raw_per_g":4.5,"raw_per_bag":5,"categories":["Pain","Blood Stasis","Women's Health","Gut Health","Sleep"],"tcm_functions":["Invigorates blood","Moves Qi","Relieves pain (broad spectrum)","Calms Shen"],"contraindications":["Pregnancy","Blood deficiency without stasis"]},
    {"id":498,"chinese":"醋延胡索","pinyin":"Cù Yán Hú Suǒ","english":"Vinegar-processed Corydalis","extract_ratio":1.11,"raw_per_g":4.5,"raw_per_bag":5,"categories":["Pain","Women's Health","Gut Health"],"tcm_functions":["Relieves pain (enhanced - directed to Liver)","Regulates menstruation","Stops abdominal pain"],"contraindications":["Pregnancy"]},
    {"id":500,"chinese":"益母草","pinyin":"Yì Mǔ Cǎo","english":"Leonurus / Motherwort Herb","extract_ratio":1.82,"raw_per_g":5.5,"raw_per_bag":10,"categories":["Women's Health","Blood Stasis","Gynecology","Kidney","Urinary"],"tcm_functions":["Invigorates blood","Regulates menstruation","Promotes urination","Reduces edema","Clears heat toxins"],"contraindications":["Pregnancy","Heavy menstruation","Blood deficiency"]},
    {"id":502,"chinese":"薏苡仁","pinyin":"Yì Yǐ Rén","english":"Coix Seed / Job's Tears","extract_ratio":2.0,"raw_per_g":5,"raw_per_bag":10,"categories":["Damp","Spleen","Gut Health","Joints","Skin","Anti-Tumor"],"tcm_functions":["Strengthens Spleen","Resolves dampness","Clears heat","Stops diarrhoea","Expels pus","Anti-tumor support"],"contraindications":["Pregnancy","Constipation"]},
    {"id":503,"chinese":"麸炒薏苡仁","pinyin":"Fū Chǎo Yì Yǐ Rén","english":"Bran-fried Coix Seed","extract_ratio":2.0,"raw_per_g":5,"raw_per_bag":10,"categories":["Spleen","Gut Health","Damp"],"tcm_functions":["Tonifies Spleen (enhanced)","Resolves dampness","Stops diarrhoea"],"contraindications":[]},
    {"id":508,"chinese":"淫羊藿(淫羊藿)","pinyin":"Yín Yáng Huò","english":"Epimedium / Horny Goat Weed","extract_ratio":1.2,"raw_per_g":5,"raw_per_bag":6,"categories":["Kidney Yang","Men's Health","Aging","Joints","Thyroid","Menopause"],"tcm_functions":["Tonifies Kidney Yang","Strengthens sinews and bones","Expels wind-cold-damp","Supports sexual function","Benefits bone density"],"contraindications":["Yin deficiency fire","Excess heat"]},
    {"id":514,"chinese":"玉竹","pinyin":"Yù Zhú","english":"Polygonatum Odoratum Rhizome / Solomon's Seal","extract_ratio":4.17,"raw_per_g":1.2,"raw_per_bag":5,"categories":["Yin Tonic","Lung","Stomach","Aging","Skin","Heart"],"tcn_functions":["Nourishes Lung and Stomach yin","Generates fluids","Clears heat","Benefits skin"],"contraindications":["Phlegm-damp","Spleen deficiency"]},
    {"id":515,"chinese":"远志(远志)","pinyin":"Yuǎn Zhì","english":"Polygala Root","extract_ratio":1.25,"raw_per_g":2.4,"raw_per_bag":3,"categories":["Sleep","Calm-Shen","Heart","Cognitive","Phlegm"],"tcm_functions":["Calms Shen","Opens orifices","Resolves phlegm","Connects Heart-Kidney","Improves memory","Reduces anxiety"],"contraindications":["Peptic ulcer","Excess heat","Raw form: GI irritation"]},
    {"id":516,"chinese":"蜜远志(远志)","pinyin":"Mì Yuǎn Zhì","english":"Honey-processed Polygala Root","extract_ratio":1.76,"raw_per_g":1.7,"raw_per_bag":3,"categories":["Sleep","Calm-Shen","Cognitive"],"tcm_functions":["Calms Shen (gentler)","Nourishes Heart","Improves sleep","Reduces phlegm"],"contraindications":[]},
    {"id":517,"chinese":"制远志(远志)","pinyin":"Zhì Yuǎn Zhì","english":"Processed Polygala Root","extract_ratio":1.3,"raw_per_g":2.3,"raw_per_bag":3,"categories":["Sleep","Calm-Shen","Cognitive","Heart"],"tcm_functions":["Calms Shen","Opens orifices (reduced GI irritation)","Connects Heart-Kidney","Improves memory"],"contraindications":["Peptic ulcer (mild caution)"]},
    {"id":519,"chinese":"银杏叶","pinyin":"Yín Xìng Yè","english":"Ginkgo Biloba Leaf","extract_ratio":2.86,"raw_per_g":3.5,"raw_per_bag":10,"categories":["Cardiovascular","Cognitive","Aging","Respiratory","Eyes"],"tcm_functions":["Invigorates blood","Stops pain","Astringes Lung","Improves circulation","Benefits cognitive function"],"contraindications":["Blood thinners (interaction)","Pregnancy"]},
    {"id":522,"chinese":"泽泻(泽泻)","pinyin":"Zé Xiè","english":"Alisma Rhizome / Water Plantain","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Urinary","Damp","Kidney","Metabolic"],"tcm_functions":["Promotes urination","Drains damp-heat","Clears Kidney fire","Reduces cholesterol"],"contraindications":["Kidney deficiency without damp-heat"]},
    {"id":524,"chinese":"浙贝母","pinyin":"Zhè Bèi Mǔ","english":"Zhejiang Fritillaria Bulb","extract_ratio":1.25,"raw_per_g":4,"raw_per_bag":5,"categories":["Phlegm","Thyroid","Respiratory","Nodules","Anti-Tumor"],"tcm_functions":["Clears heat","Resolves phlegm","Dissipates nodules","Softens hardness","Reduces masses"],"contraindications":["Cold phlegm cough","Incompatible with 川乌 Chuan Wu"]},
    {"id":525,"chinese":"知母","pinyin":"Zhī Mǔ","english":"Anemarrhena Rhizome","extract_ratio":3.34,"raw_per_g":1.8,"raw_per_bag":6,"categories":["Clear-Heat","Yin Tonic","Menopause","Thyroid","Fever"],"tcm_functions":["Clears heat","Nourishes yin","Reduces Empty Fire","Moistens dryness","Treats hot flushes"],"contraindications":["Spleen deficiency cold","Diarrhoea"]},
    {"id":526,"chinese":"盐知母","pinyin":"Yán Zhī Mǔ","english":"Salt-processed Anemarrhena","extract_ratio":3.53,"raw_per_g":1.7,"raw_per_bag":6,"categories":["Clear-Heat","Yin Tonic","Menopause","Kidney"],"tcm_functions":["Clears Kidney fire (directed)","Nourishes Kidney yin","Reduces Empty Heat","Treats night sweats and hot flushes"],"contraindications":["Spleen deficiency","Diarrhoea"]},
    {"id":527,"chinese":"枳壳","pinyin":"Zhǐ Ké","english":"Bitter Orange Immature Fruit (older)","extract_ratio":1.43,"raw_per_g":3.5,"raw_per_bag":5,"categories":["Qi-Moving","Gut Health","Liver","Prolapse"],"tcm_functions":["Promotes Qi movement","Relieves distension","Transforms phlegm","Raises prolapse"],"contraindications":["Pregnancy","Qi deficiency","Spleen deficiency"]},
    {"id":529,"chinese":"枳实(酸橙)","pinyin":"Zhǐ Shí","english":"Immature Bitter Orange Fruit","extract_ratio":1.5,"raw_per_g":3.3,"raw_per_bag":5,"categories":["Qi-Moving","Gut Health","Phlegm","Stagnation"],"tcm_functions":["Breaks Qi stagnation","Reduces accumulation","Transforms phlegm","Unblocks stool"],"contraindications":["Pregnancy","Spleen-Stomach deficiency","Qi deficiency"]},
    {"id":531,"chinese":"焦栀子","pinyin":"Jiāo Zhī Zǐ","english":"Charred Cape Jasmine Fruit","extract_ratio":2.0,"raw_per_g":3,"raw_per_bag":6,"categories":["Hemostasis","Clear-Heat","Gut Health"],"tcm_functions":["Stops bleeding","Clears heat","Resolves damp-heat"],"contraindications":["Deficiency cold"]},
    {"id":532,"chinese":"栀子","pinyin":"Zhī Zǐ","english":"Gardenia Fruit / Cape Jasmine Fruit","extract_ratio":2.0,"raw_per_g":3,"raw_per_bag":6,"categories":["Clear-Heat","Sleep","Liver","Urinary","Thyroid"],"tcm_functions":["Clears heat","Resolves irritability","Calms Shen","Cools blood","Promotes urination","Reduces jaundice"],"contraindications":["Spleen deficiency cold","Diarrhoea"]},
    {"id":151,"chinese":"浮小麦","pinyin":"Fú Xiǎo Mài","english":"Light Wheat Grain","extract_ratio":0.5,"raw_per_g":10,"raw_per_bag":5,"categories":["Sweating","Menopause","Calm-Shen","Women's Health"],"tcm_functions":["Stops excessive sweating","Clears Heat","Calms Shen","Treats night sweats and hot flushes"],"contraindications":[]},
    {"id":216,"chinese":"黄柏","pinyin":"Huáng Bǎi","english":"Phellodendron Bark / Amur Cork Tree Bark","extract_ratio":1.2,"raw_per_g":5,"raw_per_bag":6,"categories":["Clear-Damp-Heat","Kidney","Menopause","Thyroid","Skin"],"tcm_functions":["Clears heat","Dries dampness","Purges Kidney fire","Clears Empty Heat","Anti-inflammatory"],"contraindications":["Spleen-Stomach deficiency cold"]},
    {"id":217,"chinese":"盐黄柏","pinyin":"Yán Huáng Bǎi","english":"Salt-processed Phellodendron Bark","extract_ratio":1.5,"raw_per_g":4,"raw_per_bag":6,"categories":["Kidney","Menopause","Clear-Heat"],"tcm_functions":["Clears Kidney fire (directed)","Drains Empty Heat","Treats night sweats and hot flushes"],"contraindications":["Spleen deficiency cold"]},
]

# ─── CATEGORY KEYWORD MAP ────────────────────────────────────────────────────
# Maps user condition keywords to relevant herb categories
CONDITION_CATEGORY_MAP = {
    "sleep": ["Sleep", "Calm-Shen", "Heart", "Stress"],
    "insomnia": ["Sleep", "Calm-Shen", "Heart"],
    "stress": ["Liver", "Stress", "Calm-Shen", "Qi-Moving", "Women's Health"],
    "anxiety": ["Calm-Shen", "Sleep", "Heart", "Stress", "Liver"],
    "depression": ["Liver", "Stress", "Qi-Moving", "Calm-Shen"],
    "thyroid": ["Thyroid", "Nodules", "Liver", "Clear-Heat", "Blood Stasis"],
    "nodule": ["Thyroid", "Nodules", "Blood Stasis", "Phlegm"],
    "women": ["Women's Health", "Blood Tonic", "Gynecology", "Menopause"],
    "menstrual": ["Women's Health", "Blood Stasis", "Blood Tonic", "Gynecology"],
    "menopause": ["Menopause", "Yin Tonic", "Women's Health", "Sweating", "Clear-Heat"],
    "hot flush": ["Menopause", "Yin Tonic", "Clear-Heat", "Sweating"],
    "gut": ["Gut Health", "Spleen", "Damp", "Qi-Moving"],
    "digestion": ["Gut Health", "Food Stagnation", "Spleen", "Qi-Moving"],
    "ibs": ["Gut Health", "Spleen", "Damp", "Liver"],
    "bloating": ["Gut Health", "Qi-Moving", "Spleen", "Food Stagnation"],
    "aging": ["Aging", "Yin Tonic", "Qi Tonic", "Kidney", "Adaptogen"],
    "longevity": ["Aging", "Adaptogen", "Yin Tonic", "Qi Tonic"],
    "energy": ["Qi Tonic", "Adaptogen", "Spleen", "Aging"],
    "fatigue": ["Qi Tonic", "Spleen", "Kidney", "Adaptogen"],
    "blood": ["Blood Tonic", "Blood Stasis", "Women's Health", "Hemostasis"],
    "hair": ["Blood Tonic", "Yin Tonic", "Kidney", "Hair"],
    "kidney": ["Kidney", "Kidney Yang", "Yin Tonic", "Aging"],
    "men": ["Kidney Yang", "Men's Health", "Aging", "Qi Tonic"],
    "libido": ["Kidney Yang", "Men's Health", "Yang Tonic"],
    "immune": ["Immune", "Qi Tonic", "Clear-Heat", "Antiviral", "Adaptogen"],
    "respiratory": ["Respiratory", "Lung", "Phlegm"],
    "cough": ["Respiratory", "Lung Yin", "Phlegm"],
    "pain": ["Pain", "Blood Stasis", "Qi-Moving", "Warming"],
    "skin": ["Skin", "Clear-Heat", "Damp-Heat", "Blood Tonic"],
}

def get_all_herbs():
    return HERBS

def filter_herbs_by_condition(condition_text: str, max_herbs: int = 80):
    """Filter herbs relevant to a given condition using keyword matching."""
    condition_lower = condition_text.lower()
    relevant_categories = set()

    for keyword, categories in CONDITION_CATEGORY_MAP.items():
        if keyword in condition_lower:
            relevant_categories.update(categories)

    if not relevant_categories:
        # Fallback: return all herbs
        return HERBS[:max_herbs]

    scored = []
    for herb in HERBS:
        score = sum(1 for cat in herb.get("categories", []) if cat in relevant_categories)
        if score > 0:
            scored.append((score, herb))

    scored.sort(key=lambda x: -x[0])
    return [h for _, h in scored[:max_herbs]]

def format_herb_list_for_prompt(herbs: list) -> str:
    """Format herb list for LLM prompt."""
    lines = ["ID | Chinese | English | Extract Ratio | Raw/g | Categories | TCM Functions"]
    lines.append("-" * 100)
    for h in herbs:
        cats = ", ".join(h.get("categories", []))
        funcs = "; ".join(h.get("tcm_functions", [])[:3])
        lines.append(
            f"{h['id']} | {h['chinese']} | {h.get('english','N/A')} | "
            f"{h['extract_ratio']} | {h['raw_per_g']}g | {cats} | {funcs}"
        )
    return "\n".join(lines)

def get_herb_by_chinese(chinese_name: str):
    """Find herb by Chinese name."""
    for herb in HERBS:
        if herb["chinese"] in chinese_name or chinese_name in herb["chinese"]:
            return herb
    return None
